fix: replace window for globalThis
nbesli/pdf-merger-js pull request #115
Opened 2023-03-31 03:35 UTC by davbrito

This change allows the library to run on web browsers, where `window` is not defined.

2023-04-01 10:40 UTC, mojoaxel commented
@davbrito Thanks, for this clean and useful pull-request!

2023-04-01 10:43 UTC, mojoaxel requested changes
Please run `npm run standard:fix` to adjust your code to our coding style. This should fix the automatic tests! thx!

2023-04-03 14:35 UTC, davbrito commented
> Please run `npm run standard:fix` to adjust your code to our coding style. This should fix the automatic tests! thx!

Done

2023-04-11 21:10 UTC, mojoaxel approved these changes
LGTM
@davbrito Thanks!

2023-04-11 21:11 UTC, merged